CREATE TABLE supply_type (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id          BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    category        VARCHAR(20) NOT NULL,
    unit            VARCHAR(20) NOT NULL,
    properties      JSONB NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_supply_type_org ON supply_type(org_id);

CREATE TABLE supply_inventory (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id          BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    supply_type_id  BIGINT NOT NULL REFERENCES supply_type(id) ON DELETE CASCADE,
    quantity        NUMERIC(12,2) NOT NULL CHECK (quantity >= 0),
    cost_sek        INTEGER,
    season_id       BIGINT REFERENCES season(id) ON DELETE SET NULL,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_supply_inventory_org ON supply_inventory(org_id);
CREATE INDEX idx_supply_inventory_type ON supply_inventory(supply_type_id);
