-- Workflow templates
CREATE TABLE workflow_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_workflow_template_org ON workflow_template(org_id);

-- Workflow template steps
CREATE TABLE workflow_template_step (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id          BIGINT NOT NULL REFERENCES workflow_template(id) ON DELETE CASCADE,
    name                 VARCHAR(255) NOT NULL,
    description          TEXT,
    event_type           VARCHAR(50),
    days_after_previous  INTEGER,
    is_optional          BOOLEAN NOT NULL DEFAULT false,
    is_side_branch       BOOLEAN NOT NULL DEFAULT false,
    side_branch_name     VARCHAR(255),
    sort_order           INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_workflow_template_step_template ON workflow_template_step(template_id);

-- Species workflow steps (copied from template, editable per species)
CREATE TABLE species_workflow_step (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id           BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    template_step_id     BIGINT REFERENCES workflow_template_step(id) ON DELETE SET NULL,
    name                 VARCHAR(255) NOT NULL,
    description          TEXT,
    event_type           VARCHAR(50),
    days_after_previous  INTEGER,
    is_optional          BOOLEAN NOT NULL DEFAULT false,
    is_side_branch       BOOLEAN NOT NULL DEFAULT false,
    side_branch_name     VARCHAR(255),
    sort_order           INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_species_workflow_step_species ON species_workflow_step(species_id);

-- Link species to its source template (for re-sync)
ALTER TABLE species ADD COLUMN workflow_template_id BIGINT REFERENCES workflow_template(id) ON DELETE SET NULL;

-- Plant workflow progress
CREATE TABLE plant_workflow_progress (
    plant_id      BIGINT NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    step_id       BIGINT NOT NULL REFERENCES species_workflow_step(id) ON DELETE CASCADE,
    completed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (plant_id, step_id)
);

CREATE INDEX idx_plant_workflow_progress_plant ON plant_workflow_progress(plant_id);
CREATE INDEX idx_plant_workflow_progress_step ON plant_workflow_progress(step_id);
