-- Weather observations per garden, one row per (garden, date, observation_type).
-- ACTUAL arrives the morning after the day it describes.
-- FORECAST is overwritten each refresh; ACTUAL sits beside the final FORECAST for error studies.

CREATE TABLE daily_weather (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garden_id           BIGINT       NOT NULL REFERENCES garden(id) ON DELETE CASCADE,
    date                DATE         NOT NULL,
    observation_type    VARCHAR(16)  NOT NULL CHECK (observation_type IN ('ACTUAL', 'FORECAST')),
    temp_min_c          DOUBLE PRECISION,
    temp_max_c          DOUBLE PRECISION,
    temp_mean_c         DOUBLE PRECISION,
    precipitation_mm    DOUBLE PRECISION,
    wind_max_ms         DOUBLE PRECISION,
    humidity_pct        DOUBLE PRECISION,
    fetched_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_daily_weather_garden_date_type UNIQUE (garden_id, date, observation_type)
);
CREATE INDEX idx_daily_weather_garden_date ON daily_weather(garden_id, date);

-- Per-garden status of the 3-year actuals backfill. NULL means not yet attempted.
ALTER TABLE garden ADD COLUMN weather_backfill_status VARCHAR(16);
