-- =============================================================================
-- Verdant consolidated schema
-- =============================================================================

-- Users of the application
CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_subject  VARCHAR(255) UNIQUE,
    email           VARCHAR(255) NOT NULL,
    display_name    VARCHAR(255) NOT NULL,
    avatar_url      TEXT,
    password_hash   VARCHAR(255),
    role            VARCHAR(20)  NOT NULL DEFAULT 'USER',
    language        VARCHAR(5)   DEFAULT 'sv',
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ  DEFAULT now()
);

-- A physical garden owned by a user
CREATE TABLE garden (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    emoji           VARCHAR(10)  DEFAULT '🌱',
    owner_id        BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    address         TEXT,
    boundary_json   TEXT,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ  DEFAULT now()
);

-- A planting bed within a garden
CREATE TABLE bed (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    garden_id       BIGINT       NOT NULL REFERENCES garden(id) ON DELETE CASCADE,
    boundary_json   TEXT,
    length_meters   DOUBLE PRECISION,
    width_meters    DOUBLE PRECISION,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ  DEFAULT now()
);

-- Grouping for species (user_id NULL = system/global group)
CREATE TABLE species_group (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       REFERENCES app_user(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL
);

-- Plant species catalog (user_id NULL = system/global species)
CREATE TABLE species (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT       REFERENCES app_user(id) ON DELETE CASCADE,
    common_name               VARCHAR(255) NOT NULL,
    variant_name              VARCHAR(255),
    common_name_sv            VARCHAR(255),
    variant_name_sv           VARCHAR(255),
    scientific_name           VARCHAR(255),
    image_front_url           TEXT,
    image_back_url            TEXT,
    days_to_sprout            INTEGER,
    days_to_harvest           INTEGER,
    germination_time_days     INTEGER,
    sowing_depth_mm           INTEGER,
    growing_positions         TEXT         DEFAULT '',
    soils                     TEXT         DEFAULT '',
    height_cm                 INTEGER,
    bloom_months              TEXT         DEFAULT '',
    sowing_months             TEXT         DEFAULT '',
    germination_rate          INTEGER,
    group_id                  BIGINT       REFERENCES species_group(id) ON DELETE SET NULL,
    cost_per_seed_sek       INTEGER,
    expected_stems_per_plant  INTEGER,
    expected_vase_life_days   INTEGER,
    plant_type                VARCHAR(20)  DEFAULT 'ANNUAL',
    created_at                TIMESTAMPTZ  DEFAULT now()
);

-- User-defined tags for species (user_id NULL = system/global tag)
CREATE TABLE species_tag (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       REFERENCES app_user(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL
);

-- Many-to-many link between species and tags
CREATE TABLE species_tag_mapping (
    species_id      BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    tag_id          BIGINT NOT NULL REFERENCES species_tag(id) ON DELETE CASCADE,
    PRIMARY KEY (species_id, tag_id)
);

-- Additional photos for a species
CREATE TABLE species_photo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id      BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    image_url       TEXT         NOT NULL,
    sort_order      INTEGER      DEFAULT 0,
    created_at      TIMESTAMPTZ  DEFAULT now()
);

-- Seed/bulb providers (e.g. Impecta, Nelson Garden)
CREATE TABLE provider (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    identifier      VARCHAR(100) NOT NULL UNIQUE
);

-- Link between species and providers, with provider-specific images and product page
CREATE TABLE species_provider (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id          BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    provider_id         BIGINT       NOT NULL REFERENCES provider(id) ON DELETE CASCADE,
    image_front_url     TEXT,
    image_back_url      TEXT,
    product_url         TEXT,
    cost_per_unit_sek   INTEGER,
    unit_type           VARCHAR(20)  DEFAULT 'SEED',
    created_at          TIMESTAMPTZ  DEFAULT now(),
    UNIQUE (species_id, provider_id)
);

-- A growing season with frost dates and parameters
CREATE TABLE season (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    name                    VARCHAR(100) NOT NULL,
    year                    INTEGER      NOT NULL,
    start_date              DATE,
    end_date                DATE,
    last_frost_date         DATE,
    first_frost_date        DATE,
    growing_degree_base_c   DOUBLE PRECISION DEFAULT 10.0,
    notes                   TEXT,
    is_active               BOOLEAN      DEFAULT true,
    created_at              TIMESTAMPTZ  DEFAULT now(),
    updated_at              TIMESTAMPTZ  DEFAULT now(),
    UNIQUE (user_id, name)
);

-- A customer or sales channel for flower production
CREATE TABLE customer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    name            VARCHAR(200) NOT NULL,
    channel         VARCHAR(50)  NOT NULL,
    contact_info    TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    UNIQUE (user_id, name)
);

-- An individual plant or batch of plants being tracked
CREATE TABLE plant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    species_id      BIGINT       REFERENCES species(id) ON DELETE SET NULL,
    planted_date    DATE,
    status          VARCHAR(30)  NOT NULL DEFAULT 'SEEDED',
    seed_count      INTEGER,
    surviving_count INTEGER,
    bed_id          BIGINT       REFERENCES bed(id) ON DELETE CASCADE,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    season_id       BIGINT       REFERENCES season(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ  DEFAULT now()
);

-- Timeline events for a plant (sowing, potting up, harvest, etc.)
CREATE TABLE plant_event (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id                 BIGINT       NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    event_type               VARCHAR(30)  NOT NULL,
    event_date               DATE         NOT NULL DEFAULT CURRENT_DATE,
    plant_count              INTEGER,
    weight_grams             DOUBLE PRECISION,
    quantity                 INTEGER,
    notes                    TEXT,
    image_url                TEXT,
    ai_suggestions           TEXT,
    stem_count               INTEGER,
    stem_length_cm           INTEGER,
    quality_grade            VARCHAR(1),
    vase_life_days           INTEGER,
    harvest_destination_id   BIGINT       REFERENCES customer(id) ON DELETE SET NULL,
    created_at               TIMESTAMPTZ  DEFAULT now()
);

-- Frequently used comments per user
CREATE TABLE frequent_comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    text            TEXT         NOT NULL,
    use_count       INTEGER      DEFAULT 1,
    UNIQUE (user_id, text)
);

-- Seed inventory tracking
CREATE TABLE seed_inventory (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    species_id          BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    quantity            INTEGER      NOT NULL CHECK (quantity >= 0),
    collection_date     DATE,
    expiration_date     DATE,
    cost_per_unit_sek   INTEGER,
    unit_type           VARCHAR(20)  DEFAULT 'SEED',
    season_id           BIGINT       REFERENCES season(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ  DEFAULT now()
);

-- Succession planting schedule for a species within a season
CREATE TABLE succession_schedule (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    season_id               BIGINT       NOT NULL REFERENCES season(id) ON DELETE CASCADE,
    species_id              BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    bed_id                  BIGINT       REFERENCES bed(id) ON DELETE SET NULL,
    first_sow_date          DATE         NOT NULL,
    interval_days           INTEGER      NOT NULL,
    total_successions       INTEGER      NOT NULL,
    seeds_per_succession    INTEGER      NOT NULL,
    notes                   TEXT,
    created_at              TIMESTAMPTZ  DEFAULT now()
);

-- Scheduled gardening tasks (sowing, transplanting, etc.)
CREATE TABLE scheduled_task (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    species_id              BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    activity_type           VARCHAR(50)  NOT NULL,
    deadline                DATE         NOT NULL,
    target_count            INTEGER      NOT NULL,
    remaining_count         INTEGER      NOT NULL,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    notes                   TEXT,
    season_id               BIGINT       REFERENCES season(id) ON DELETE SET NULL,
    succession_schedule_id  BIGINT       REFERENCES succession_schedule(id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ  DEFAULT now(),
    updated_at              TIMESTAMPTZ  DEFAULT now()
);

-- Log of pest, disease, or deficiency observations
CREATE TABLE pest_disease_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    season_id       BIGINT       REFERENCES season(id) ON DELETE SET NULL,
    bed_id          BIGINT       REFERENCES bed(id) ON DELETE SET NULL,
    species_id      BIGINT       REFERENCES species(id) ON DELETE SET NULL,
    observed_date   DATE         NOT NULL DEFAULT CURRENT_DATE,
    category        VARCHAR(20)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    severity        VARCHAR(10)  NOT NULL DEFAULT 'MODERATE',
    treatment       TEXT,
    outcome         VARCHAR(20),
    notes           TEXT,
    image_url       TEXT,
    created_at      TIMESTAMPTZ  DEFAULT now()
);

-- Variety trial records for comparing species performance across seasons
CREATE TABLE variety_trial (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    season_id           BIGINT       NOT NULL REFERENCES season(id) ON DELETE CASCADE,
    species_id          BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    bed_id              BIGINT       REFERENCES bed(id) ON DELETE SET NULL,
    plant_count         INTEGER,
    stem_yield          INTEGER,
    avg_stem_length_cm  INTEGER,
    avg_vase_life_days  INTEGER,
    quality_score       INTEGER,
    customer_reception  VARCHAR(20),
    verdict             VARCHAR(20)  NOT NULL DEFAULT 'UNDECIDED',
    notes               TEXT,
    created_at          TIMESTAMPTZ  DEFAULT now()
);

-- Bouquet design recipes
CREATE TABLE bouquet_recipe (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    name            VARCHAR(200) NOT NULL,
    description     TEXT,
    image_url       TEXT,
    price_sek       INTEGER,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ  DEFAULT now()
);

-- Individual species items within a bouquet recipe
CREATE TABLE bouquet_recipe_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id       BIGINT       NOT NULL REFERENCES bouquet_recipe(id) ON DELETE CASCADE,
    species_id      BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    stem_count      INTEGER      NOT NULL,
    role            VARCHAR(30)  DEFAULT 'FLOWER',
    notes           TEXT
);

-- Weekly stem production targets per species per season
CREATE TABLE production_target (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    season_id       BIGINT       NOT NULL REFERENCES season(id) ON DELETE CASCADE,
    species_id      BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    stems_per_week  INTEGER      NOT NULL,
    start_date      DATE         NOT NULL,
    end_date        DATE         NOT NULL,
    notes           TEXT,
    created_at      TIMESTAMPTZ  DEFAULT now()
);

-- =============================================================================
-- Indexes on foreign key columns
-- =============================================================================

CREATE INDEX idx_garden_owner_id ON garden(owner_id);

CREATE INDEX idx_bed_garden_id ON bed(garden_id);

CREATE INDEX idx_species_group_user_id ON species_group(user_id);

CREATE INDEX idx_species_user_id ON species(user_id);
CREATE INDEX idx_species_group_id ON species(group_id);

CREATE INDEX idx_species_tag_user_id ON species_tag(user_id);

CREATE INDEX idx_species_tag_mapping_species_id ON species_tag_mapping(species_id);
CREATE INDEX idx_species_tag_mapping_tag_id ON species_tag_mapping(tag_id);

CREATE INDEX idx_species_photo_species_id ON species_photo(species_id);

CREATE INDEX idx_species_provider_species_id ON species_provider(species_id);
CREATE INDEX idx_species_provider_provider_id ON species_provider(provider_id);

CREATE INDEX idx_season_user_id ON season(user_id);

CREATE INDEX idx_customer_user_id ON customer(user_id);

CREATE INDEX idx_plant_species_id ON plant(species_id);
CREATE INDEX idx_plant_bed_id ON plant(bed_id);
CREATE INDEX idx_plant_user_id ON plant(user_id);
CREATE INDEX idx_plant_season_id ON plant(season_id);

CREATE INDEX idx_plant_event_plant_id ON plant_event(plant_id);
CREATE INDEX idx_plant_event_harvest_destination_id ON plant_event(harvest_destination_id);

CREATE INDEX idx_frequent_comment_user_id ON frequent_comment(user_id);

CREATE INDEX idx_seed_inventory_user_id ON seed_inventory(user_id);
CREATE INDEX idx_seed_inventory_species_id ON seed_inventory(species_id);
CREATE INDEX idx_seed_inventory_season_id ON seed_inventory(season_id);

CREATE INDEX idx_succession_schedule_user_id ON succession_schedule(user_id);
CREATE INDEX idx_succession_schedule_season_id ON succession_schedule(season_id);
CREATE INDEX idx_succession_schedule_species_id ON succession_schedule(species_id);
CREATE INDEX idx_succession_schedule_bed_id ON succession_schedule(bed_id);

CREATE INDEX idx_scheduled_task_user_id ON scheduled_task(user_id);
CREATE INDEX idx_scheduled_task_species_id ON scheduled_task(species_id);
CREATE INDEX idx_scheduled_task_season_id ON scheduled_task(season_id);
CREATE INDEX idx_scheduled_task_succession_schedule_id ON scheduled_task(succession_schedule_id);

CREATE INDEX idx_pest_disease_log_user_id ON pest_disease_log(user_id);
CREATE INDEX idx_pest_disease_log_season_id ON pest_disease_log(season_id);
CREATE INDEX idx_pest_disease_log_bed_id ON pest_disease_log(bed_id);
CREATE INDEX idx_pest_disease_log_species_id ON pest_disease_log(species_id);

CREATE INDEX idx_variety_trial_user_id ON variety_trial(user_id);
CREATE INDEX idx_variety_trial_season_id ON variety_trial(season_id);
CREATE INDEX idx_variety_trial_species_id ON variety_trial(species_id);
CREATE INDEX idx_variety_trial_bed_id ON variety_trial(bed_id);

CREATE INDEX idx_bouquet_recipe_user_id ON bouquet_recipe(user_id);

CREATE INDEX idx_bouquet_recipe_item_recipe_id ON bouquet_recipe_item(recipe_id);
CREATE INDEX idx_bouquet_recipe_item_species_id ON bouquet_recipe_item(species_id);

CREATE INDEX idx_production_target_user_id ON production_target(user_id);
CREATE INDEX idx_production_target_season_id ON production_target(season_id);
CREATE INDEX idx_production_target_species_id ON production_target(species_id);

-- =============================================================================
-- Default data
-- =============================================================================

INSERT INTO provider (name, identifier) VALUES ('Impecta', 'impecta');
INSERT INTO provider (name, identifier) VALUES ('Florea', 'florea');
INSERT INTO provider (name, identifier) VALUES ('Wexthuset', 'wexthuset');

-- =============================================================================
-- Marketplace
-- =============================================================================

-- Listing: producer publishes available stems for sale
CREATE TABLE listing (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    species_id          BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    title               VARCHAR(255) NOT NULL,
    description         TEXT,
    quantity_available  INTEGER      NOT NULL CHECK (quantity_available >= 0),
    price_per_stem_sek  INTEGER     NOT NULL,
    available_from      DATE         NOT NULL,
    available_until     DATE         NOT NULL,
    image_url           TEXT,
    is_active           BOOLEAN      DEFAULT true,
    created_at          TIMESTAMPTZ  DEFAULT now(),
    updated_at          TIMESTAMPTZ  DEFAULT now()
);
CREATE INDEX idx_listing_user ON listing(user_id);
CREATE INDEX idx_listing_species ON listing(species_id);
CREATE INDEX idx_listing_active ON listing(is_active, available_from, available_until);

-- Market order: purchaser places order
CREATE TABLE market_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchaser_id    BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    producer_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PLACED',
    delivery_date   DATE,
    total_sek       INTEGER      NOT NULL DEFAULT 0,
    notes           TEXT,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ  DEFAULT now()
);
CREATE INDEX idx_market_order_purchaser ON market_order(purchaser_id);
CREATE INDEX idx_market_order_producer ON market_order(producer_id);

-- Order item: line items in an order
CREATE TABLE order_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT       NOT NULL REFERENCES market_order(id) ON DELETE CASCADE,
    listing_id          BIGINT       NOT NULL REFERENCES listing(id) ON DELETE CASCADE,
    species_id          BIGINT       NOT NULL REFERENCES species(id) ON DELETE SET NULL,
    species_name        VARCHAR(255) NOT NULL,
    quantity            INTEGER      NOT NULL CHECK (quantity > 0),
    price_per_stem_sek  INTEGER     NOT NULL CHECK (price_per_stem_sek >= 0)
);
CREATE INDEX idx_order_item_order ON order_item(order_id);

CREATE INDEX idx_plant_event_type ON plant_event(plant_id, event_type);
CREATE INDEX idx_plant_user_season ON plant(user_id, season_id);
