-- Generic supply application (fertilizer first consumer).

CREATE TABLE supply_application (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id               BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    bed_id               BIGINT NOT NULL REFERENCES bed(id) ON DELETE CASCADE,
    supply_inventory_id  BIGINT NOT NULL REFERENCES supply_inventory(id),
    supply_type_id       BIGINT NOT NULL REFERENCES supply_type(id),
    quantity             NUMERIC(12,2) NOT NULL CHECK (quantity > 0),
    target_scope         VARCHAR(8) NOT NULL CHECK (target_scope IN ('BED','PLANTS')),
    applied_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_by           BIGINT NOT NULL REFERENCES app_user(id),
    workflow_step_id     BIGINT REFERENCES species_workflow_step(id) ON DELETE SET NULL,
    notes                TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_supply_application_bed       ON supply_application(bed_id, applied_at DESC);
CREATE INDEX idx_supply_application_inventory ON supply_application(supply_inventory_id);
CREATE INDEX idx_supply_application_org       ON supply_application(org_id, applied_at DESC);

-- plant_event gains the APPLIED_SUPPLY case (enum is a Kotlin-only concept; column is VARCHAR already).
ALTER TABLE plant_event ADD COLUMN supply_application_id
    BIGINT REFERENCES supply_application(id) ON DELETE SET NULL;
CREATE INDEX idx_plant_event_supply_application ON plant_event(supply_application_id);

-- Workflow step tables get two optional suggestion columns, used only when event_type = 'APPLIED_SUPPLY'.
ALTER TABLE workflow_template_step
    ADD COLUMN suggested_supply_type_id BIGINT REFERENCES supply_type(id) ON DELETE SET NULL,
    ADD COLUMN suggested_quantity       NUMERIC(12,2);

ALTER TABLE species_workflow_step
    ADD COLUMN suggested_supply_type_id BIGINT REFERENCES supply_type(id) ON DELETE SET NULL,
    ADD COLUMN suggested_quantity       NUMERIC(12,2);
