-- Actual built/sold bouquets, distinct from bouquet_recipe (templates).
-- Each bouquet carries its own item list (copy-on-build) and optionally
-- references the recipe it was built from for analytics rollup.

CREATE TABLE bouquet (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id             BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    source_recipe_id   BIGINT       REFERENCES bouquet_recipe(id) ON DELETE SET NULL,
    name               VARCHAR(255) NOT NULL,
    description        TEXT,
    image_url          TEXT,
    price_sek          INTEGER,
    assembled_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    notes              TEXT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE bouquet_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bouquet_id  BIGINT       NOT NULL REFERENCES bouquet(id) ON DELETE CASCADE,
    species_id  BIGINT       NOT NULL REFERENCES species(id),
    stem_count  INTEGER      NOT NULL CHECK (stem_count > 0),
    role        VARCHAR(30)  NOT NULL DEFAULT 'FLOWER',
    notes       TEXT
);

CREATE INDEX idx_bouquet_org              ON bouquet(org_id);
CREATE INDEX idx_bouquet_assembled_at     ON bouquet(org_id, assembled_at DESC);
CREATE INDEX idx_bouquet_source_recipe    ON bouquet(source_recipe_id);
CREATE INDEX idx_bouquet_item_bouquet     ON bouquet_item(bouquet_id);
