CREATE TABLE tray_location (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_tray_location_org_id ON tray_location(org_id);

ALTER TABLE plant
  ADD COLUMN tray_location_id BIGINT REFERENCES tray_location(id) ON DELETE SET NULL;
ALTER TABLE plant
  ADD CONSTRAINT plant_bed_or_tray_location_exclusive
  CHECK ((bed_id IS NULL) OR (tray_location_id IS NULL));
CREATE INDEX idx_plant_tray_location_id ON plant(tray_location_id);

ALTER TABLE plant_event
  ADD COLUMN from_tray_location_id BIGINT REFERENCES tray_location(id) ON DELETE SET NULL,
  ADD COLUMN to_tray_location_id   BIGINT REFERENCES tray_location(id) ON DELETE SET NULL;
