-- Bed-level maintenance events. Watering, weeding, and similar bed-scoped
-- activities still happen even when no plants are growing in the bed, so
-- they need their own log instead of relying on per-plant fan-out.

CREATE TABLE bed_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bed_id          BIGINT       NOT NULL REFERENCES bed(id) ON DELETE CASCADE,
    event_type      VARCHAR(32)  NOT NULL,
    event_date      DATE         NOT NULL,
    notes           TEXT,
    plants_affected INT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_bed_event_bed ON bed_event(bed_id, event_date DESC);
