ALTER TABLE garden ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE garden ADD COLUMN longitude DOUBLE PRECISION;
ALTER TABLE garden ADD COLUMN address TEXT;
ALTER TABLE garden ADD COLUMN boundary_json TEXT;

ALTER TABLE bed ADD COLUMN boundary_json TEXT;
