-- Sale tracking core tables.
--
-- outlet: a sales venue / channel instance. Distinct from customer (a buyer
-- contact). Many customers may share one outlet (CSA), and many outlets are
-- anonymous-customer (farmers market walk-up).
--
-- sale_lot: a unit of "stuff offered for sale", polymorphic over plant batch
-- (plugs/tubers/bulbs), harvest event (stems/bunches), or bouquet. Tracks the
-- running quantity_remaining, the current asking price (with the original
-- preserved for analytics), and the current outlet of intent.
--
-- sale: an actual transaction that decrements quantity_remaining. Snapshots
-- outlet_id at insert so attribution survives later change_outlet on the lot.
--
-- sale_lot_event: append-only audit log capturing every state change
-- (markdowns, outlet moves, returns, sales recorded, edits, terminal NOT_SOLD,
-- auto-flipped SOLD_OUT).

CREATE TABLE outlet (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id          BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    name            VARCHAR(200) NOT NULL,
    channel         VARCHAR(50)  NOT NULL,
    contact_info    TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (org_id, name)
);
CREATE INDEX idx_outlet_org ON outlet(org_id);

CREATE TABLE sale_lot (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id                          BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    source_kind                     VARCHAR(20)  NOT NULL,
    plant_id                        BIGINT       REFERENCES plant(id)        ON DELETE RESTRICT,
    harvest_event_id                BIGINT       REFERENCES plant_event(id)  ON DELETE RESTRICT,
    bouquet_id                      BIGINT       REFERENCES bouquet(id)      ON DELETE RESTRICT,
    unit_kind                       VARCHAR(20)  NOT NULL,
    stems_per_unit                  INTEGER,
    quantity_total                  INTEGER      NOT NULL CHECK (quantity_total > 0),
    quantity_remaining              INTEGER      NOT NULL CHECK (quantity_remaining >= 0),
    initial_requested_price_cents   INTEGER      NOT NULL CHECK (initial_requested_price_cents >= 0),
    current_requested_price_cents   INTEGER      NOT NULL CHECK (current_requested_price_cents >= 0),
    current_outlet_id               BIGINT       NOT NULL REFERENCES outlet(id) ON DELETE RESTRICT,
    status                          VARCHAR(20)  NOT NULL DEFAULT 'OFFERED',
    created_at                      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK (quantity_remaining <= quantity_total),
    CHECK (status IN ('OFFERED', 'SOLD_OUT', 'NOT_SOLD')),
    CHECK (source_kind IN ('PLANT', 'HARVEST_EVENT', 'BOUQUET')),
    CHECK (unit_kind IN ('STEM', 'BUNCH', 'PLUG', 'BULB', 'TUBER', 'PLANT', 'BOUQUET')),
    CHECK (
        (source_kind = 'PLANT'         AND plant_id         IS NOT NULL AND harvest_event_id IS NULL     AND bouquet_id IS NULL) OR
        (source_kind = 'HARVEST_EVENT' AND plant_id         IS NULL     AND harvest_event_id IS NOT NULL AND bouquet_id IS NULL) OR
        (source_kind = 'BOUQUET'       AND plant_id         IS NULL     AND harvest_event_id IS NULL     AND bouquet_id IS NOT NULL)
    ),
    -- stems_per_unit only meaningful for BUNCH; require it if BUNCH, forbid otherwise.
    CHECK (
        (unit_kind = 'BUNCH' AND stems_per_unit IS NOT NULL AND stems_per_unit > 0) OR
        (unit_kind <> 'BUNCH' AND stems_per_unit IS NULL)
    )
);
CREATE INDEX idx_sale_lot_org_status     ON sale_lot(org_id, status);
CREATE INDEX idx_sale_lot_plant          ON sale_lot(plant_id)         WHERE plant_id IS NOT NULL;
CREATE INDEX idx_sale_lot_harvest_event  ON sale_lot(harvest_event_id) WHERE harvest_event_id IS NOT NULL;
CREATE INDEX idx_sale_lot_bouquet        ON sale_lot(bouquet_id)       WHERE bouquet_id IS NOT NULL;
CREATE INDEX idx_sale_lot_current_outlet ON sale_lot(current_outlet_id);

CREATE TABLE sale (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_lot_id             BIGINT       NOT NULL REFERENCES sale_lot(id) ON DELETE RESTRICT,
    quantity                INTEGER      NOT NULL CHECK (quantity > 0),
    price_per_unit_cents    INTEGER      NOT NULL CHECK (price_per_unit_cents >= 0),
    outlet_id               BIGINT       NOT NULL REFERENCES outlet(id) ON DELETE RESTRICT,
    customer_id             BIGINT       REFERENCES customer(id)       ON DELETE SET NULL,
    sold_at                 DATE         NOT NULL DEFAULT current_date,
    recorded_by_user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    notes                   TEXT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_sale_lot              ON sale(sale_lot_id);
CREATE INDEX idx_sale_outlet_sold_at   ON sale(outlet_id, sold_at);
CREATE INDEX idx_sale_customer         ON sale(customer_id) WHERE customer_id IS NOT NULL;

CREATE TABLE sale_lot_event (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_lot_id             BIGINT       NOT NULL REFERENCES sale_lot(id) ON DELETE CASCADE,
    event_type              VARCHAR(40)  NOT NULL,
    payload_json            JSONB,
    recorded_by_user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK (event_type IN (
        'CREATED', 'PRICE_CHANGED', 'OUTLET_CHANGED', 'RETURNED_FROM_OUTLET',
        'SALE_RECORDED', 'SALE_EDITED', 'MARKED_NOT_SOLD', 'AUTO_SOLD_OUT'
    ))
);
CREATE INDEX idx_sale_lot_event_lot ON sale_lot_event(sale_lot_id, created_at);
