-- Join requests: a user without org membership asks to join an org by name.
-- The org owner approves or declines via the Android app.
CREATE TABLE org_join_request (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    status      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMPTZ  DEFAULT now(),
    UNIQUE (org_id, user_id)
);

CREATE INDEX idx_org_join_request_org_id ON org_join_request(org_id);
CREATE INDEX idx_org_join_request_user_id ON org_join_request(user_id);
