-- Add lifecycle columns to plant
ALTER TABLE plant ADD COLUMN seed_count INT;
ALTER TABLE plant ADD COLUMN surviving_count INT;

-- Migrate old status values to new ones
UPDATE plant SET status = 'SEEDED' WHERE status = 'SEEDLING';
UPDATE plant SET status = 'GROWING' WHERE status = 'MATURE';

-- Plant event timeline
CREATE TABLE plant_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id        BIGINT       NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    event_type      VARCHAR(30)  NOT NULL,
    event_date      DATE         NOT NULL DEFAULT CURRENT_DATE,
    plant_count     INT,
    weight_grams    DOUBLE PRECISION,
    quantity        INT,
    notes           TEXT,
    image_base64    TEXT,
    ai_suggestions  TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_plant_event_plant ON plant_event(plant_id);
