-- Species groups (user_id NULL = system/global group)
CREATE TABLE species_group (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT REFERENCES app_user(id) ON DELETE CASCADE,
    name     VARCHAR(255) NOT NULL
);
CREATE INDEX idx_species_group_user ON species_group(user_id);

-- Species (user_id NULL = system/global species)
CREATE TABLE species (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT REFERENCES app_user(id) ON DELETE CASCADE,
    common_name           VARCHAR(255) NOT NULL,
    scientific_name       VARCHAR(255),
    image_base64          TEXT,
    days_to_sprout        INT,
    days_to_harvest       INT,
    germination_time_days INT,
    sowing_depth_mm       INT,
    growing_positions     VARCHAR(255),
    soils                 VARCHAR(255),
    height_cm             INT,
    bloom_time            VARCHAR(100),
    germination_rate      INT,
    group_id              BIGINT REFERENCES species_group(id) ON DELETE SET NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX idx_species_user ON species(user_id);

-- Species tags (user_id NULL = system/global tag)
CREATE TABLE species_tag (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT REFERENCES app_user(id) ON DELETE CASCADE,
    name     VARCHAR(100) NOT NULL
);
CREATE INDEX idx_species_tag_user ON species_tag(user_id);

CREATE TABLE species_tag_mapping (
    species_id BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES species_tag(id) ON DELETE CASCADE,
    PRIMARY KEY (species_id, tag_id)
);

-- Add lifecycle columns to plant
ALTER TABLE plant ADD COLUMN seed_count INT;
ALTER TABLE plant ADD COLUMN surviving_count INT;

-- Replace species VARCHAR with species_id FK
ALTER TABLE plant ADD COLUMN species_id BIGINT REFERENCES species(id) ON DELETE SET NULL;

-- Migrate existing species strings to species records and link them
-- (For any existing plants with a species name, create a species record and set species_id)
INSERT INTO species (user_id, common_name, created_at)
SELECT DISTINCT g.owner_id, p.species, now()
FROM plant p
JOIN bed b ON p.bed_id = b.id
JOIN garden g ON b.garden_id = g.id
WHERE p.species IS NOT NULL AND p.species != '';

UPDATE plant SET species_id = s.id
FROM species s, bed b, garden g
WHERE plant.bed_id = b.id
  AND b.garden_id = g.id
  AND s.user_id = g.owner_id
  AND s.common_name = plant.species
  AND plant.species IS NOT NULL AND plant.species != '';

-- Drop the old species VARCHAR column
ALTER TABLE plant DROP COLUMN species;

-- Migrate old status values to new ones
UPDATE plant SET status = 'SEEDED' WHERE status = 'SEEDLING';
UPDATE plant SET status = 'GROWING' WHERE status = 'MATURE';

-- Plant event timeline
CREATE TABLE plant_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id        BIGINT       NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    event_type      VARCHAR(30)  NOT NULL,
    event_date      DATE         NOT NULL DEFAULT CURRENT_DATE,
    plant_count     INT,
    weight_grams    DOUBLE PRECISION,
    quantity         INT,
    notes           TEXT,
    image_base64    TEXT,
    ai_suggestions  TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX idx_plant_event_plant ON plant_event(plant_id);

-- Frequent comments
CREATE TABLE frequent_comment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    text      VARCHAR(500) NOT NULL,
    use_count INT NOT NULL DEFAULT 1,
    UNIQUE(user_id, text)
);
CREATE INDEX idx_frequent_comment_user ON frequent_comment(user_id);
