-- Photos taken of a bed. The bed itself is mostly static; pictures let
-- the gardener capture change over time, document issues, and provide
-- context that doesn't fit into the structured event log.

CREATE TABLE bed_photo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bed_id       BIGINT      NOT NULL REFERENCES bed(id) ON DELETE CASCADE,
    photo_url    TEXT        NOT NULL,
    reason       VARCHAR(32) NOT NULL,
    description  TEXT,
    captured_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_bed_photo_bed ON bed_photo(bed_id, captured_at DESC);
