-- Per-plant copies of workflow steps. Cloned from species_workflow_step
-- when a plant is created so the grower can later diverge (push back a
-- step, add a one-off side branch, mark a step optional for *this* plant)
-- without affecting other plants of the same species or the underlying
-- template.

CREATE TABLE plant_workflow_step (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id                 BIGINT       NOT NULL REFERENCES plant(id) ON DELETE CASCADE,
    species_step_id          BIGINT       REFERENCES species_workflow_step(id) ON DELETE SET NULL,
    name                     VARCHAR(255) NOT NULL,
    description              TEXT,
    event_type               VARCHAR(50),
    days_after_previous      INTEGER,
    is_optional              BOOLEAN      NOT NULL DEFAULT false,
    is_side_branch           BOOLEAN      NOT NULL DEFAULT false,
    side_branch_name         VARCHAR(255),
    sort_order               INTEGER      NOT NULL DEFAULT 0,
    suggested_supply_type_id BIGINT,
    suggested_quantity       NUMERIC
);

CREATE INDEX idx_plant_workflow_step_plant ON plant_workflow_step(plant_id);
CREATE INDEX idx_plant_workflow_step_species_step ON plant_workflow_step(species_step_id);

-- Backfill: every existing plant gets its own copy of its species' steps,
-- so plants that pre-date this migration keep working.
INSERT INTO plant_workflow_step (
    plant_id, species_step_id, name, description, event_type,
    days_after_previous, is_optional, is_side_branch, side_branch_name, sort_order,
    suggested_supply_type_id, suggested_quantity
)
SELECT p.id, sws.id, sws.name, sws.description, sws.event_type,
       sws.days_after_previous, sws.is_optional, sws.is_side_branch, sws.side_branch_name, sws.sort_order,
       sws.suggested_supply_type_id, sws.suggested_quantity
FROM plant p
JOIN species_workflow_step sws ON sws.species_id = p.species_id;

-- plant_workflow_progress.step_id now references plant_workflow_step
-- instead of species_workflow_step. Repoint existing rows via the
-- (plant_id, species_step_id) link, then drop any that have no matching
-- plant step (shouldn't happen after the backfill above, but defensive).
ALTER TABLE plant_workflow_progress
    DROP CONSTRAINT IF EXISTS plant_workflow_progress_step_id_fkey;

UPDATE plant_workflow_progress pwp
SET    step_id = pws.id
FROM   plant_workflow_step pws
WHERE  pws.plant_id = pwp.plant_id
  AND  pws.species_step_id = pwp.step_id;

DELETE FROM plant_workflow_progress pwp
WHERE  NOT EXISTS (SELECT 1 FROM plant_workflow_step pws WHERE pws.id = pwp.step_id);

ALTER TABLE plant_workflow_progress
    ADD CONSTRAINT plant_workflow_progress_step_id_fkey
        FOREIGN KEY (step_id) REFERENCES plant_workflow_step(id) ON DELETE CASCADE;
