-- A place in the garden that is not a growing bed but still needs work:
-- gravel walkways, lawns, hedges, compost corners. Sibling of `bed` under
-- `garden`; org scoping goes through garden.org_id exactly as bed does, so
-- there is deliberately no org_id column here.

CREATE TABLE garden_area (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garden_id     BIGINT       NOT NULL REFERENCES garden(id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    category      VARCHAR(32)  NOT NULL,
    boundary_json TEXT,
    size_sqm      DOUBLE PRECISION,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_garden_area_garden ON garden_area(garden_id);
