-- Maintenance log for an area. event_type holds a MaintenanceActivity value
-- (WEED, MOW, …) or 'NOTE'. Areas grow nothing, so there is no plants_affected
-- column and no past-tense enum — the activity name is stored as-is.

CREATE TABLE garden_area_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garden_area_id BIGINT      NOT NULL REFERENCES garden_area(id) ON DELETE CASCADE,
    event_type     VARCHAR(32) NOT NULL,
    event_date     DATE        NOT NULL,
    notes          TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_garden_area_event_area
    ON garden_area_event(garden_area_id, event_date DESC);

-- Mirrors bed_photo field for field.
CREATE TABLE garden_area_photo (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garden_area_id BIGINT      NOT NULL REFERENCES garden_area(id) ON DELETE CASCADE,
    photo_url      TEXT        NOT NULL,
    reason         VARCHAR(32) NOT NULL,
    description    TEXT,
    captured_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_garden_area_photo_area
    ON garden_area_photo(garden_area_id, captured_at DESC);
