-- Recurring maintenance. A rule targets exactly one of a bed or a garden area
-- (two nullable FKs plus a check, rather than a generic target_type/target_id
-- pair, so cascades and referential integrity still work).
--
-- Season bounds are month/day pairs, not dates, so the window repeats every
-- year. start > end means the window wraps the new year (Nov 1 – Mar 31).
--
-- There is deliberately no last_completed_at column: "last done" is derived
-- from the event log, so logging work by hand also resets the reminder.

CREATE TABLE maintenance_rule (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id             BIGINT      NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    bed_id             BIGINT      REFERENCES bed(id) ON DELETE CASCADE,
    garden_area_id     BIGINT      REFERENCES garden_area(id) ON DELETE CASCADE,
    activity_type      VARCHAR(32) NOT NULL,
    interval_days      INT         NOT NULL CHECK (interval_days >= 1),
    anchor_date        DATE,
    season_start_month SMALLINT CHECK (season_start_month BETWEEN 1 AND 12),
    season_start_day   SMALLINT CHECK (season_start_day   BETWEEN 1 AND 31),
    season_end_month   SMALLINT CHECK (season_end_month   BETWEEN 1 AND 12),
    season_end_day     SMALLINT CHECK (season_end_day     BETWEEN 1 AND 31),
    active             BOOLEAN     NOT NULL DEFAULT true,
    notes              TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT maintenance_rule_one_target CHECK (
        (bed_id IS NOT NULL)::int + (garden_area_id IS NOT NULL)::int = 1
    ),
    CONSTRAINT maintenance_rule_season_all_or_none CHECK (
        num_nonnulls(season_start_month, season_start_day,
                     season_end_month, season_end_day) IN (0, 4)
    )
);

CREATE INDEX idx_maintenance_rule_org  ON maintenance_rule(org_id);
CREATE INDEX idx_maintenance_rule_bed  ON maintenance_rule(bed_id)         WHERE bed_id IS NOT NULL;
CREATE INDEX idx_maintenance_rule_area ON maintenance_rule(garden_area_id) WHERE garden_area_id IS NOT NULL;

-- Tasks can now target an area, and can record which rule produced them.
ALTER TABLE scheduled_task
    ADD COLUMN garden_area_id      BIGINT REFERENCES garden_area(id) ON DELETE CASCADE,
    ADD COLUMN maintenance_rule_id BIGINT REFERENCES maintenance_rule(id) ON DELETE SET NULL;

CREATE INDEX idx_scheduled_task_garden_area
    ON scheduled_task(garden_area_id) WHERE garden_area_id IS NOT NULL;

-- At most one open task per rule. This is what makes the daily scheduler
-- idempotent by construction: a double run cannot produce duplicates.
CREATE UNIQUE INDEX idx_scheduled_task_open_rule
    ON scheduled_task(maintenance_rule_id)
    WHERE maintenance_rule_id IS NOT NULL AND status = 'PENDING';
