CREATE TABLE species_production_profile (
    org_id BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    species_id BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    profile JSONB NOT NULL,
    PRIMARY KEY (org_id, species_id)
);

CREATE TABLE harvest_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    season_id BIGINT REFERENCES season(id) ON DELETE SET NULL,
    request_key UUID NOT NULL,
    request JSONB NOT NULL,
    snapshot JSONB NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, request_key)
);
CREATE INDEX idx_harvest_plan_org ON harvest_plan(org_id, id DESC);

ALTER TABLE scheduled_task
    ADD COLUMN harvest_plan_id BIGINT REFERENCES harvest_plan(id),
    ADD COLUMN plan_step_key VARCHAR(100),
    ADD COLUMN quantity_unit VARCHAR(16),
    ADD CONSTRAINT scheduled_task_plan_step UNIQUE (harvest_plan_id, plan_step_key);
