CREATE TABLE seed_inventory (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    species_id      BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    quantity        INT          NOT NULL CHECK (quantity >= 0),
    collection_date DATE,
    expiration_date DATE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX idx_seed_inventory_user ON seed_inventory(user_id);
CREATE INDEX idx_seed_inventory_species ON seed_inventory(species_id);
