-- User language preference
ALTER TABLE app_user ADD COLUMN language VARCHAR(5) NOT NULL DEFAULT 'sv';

-- Species: Swedish trivial name
ALTER TABLE species ADD COLUMN common_name_sv VARCHAR(255);

-- Species: Swedish variant name
ALTER TABLE species ADD COLUMN variant_name_sv VARCHAR(255);

-- Species: auxiliary photos
CREATE TABLE species_photo (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    image_url  TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX idx_species_photo_species ON species_photo(species_id);
