CREATE TABLE scheduled_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    species_id      BIGINT       NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    activity_type   VARCHAR(30)  NOT NULL,
    deadline        DATE         NOT NULL,
    target_count    INT          NOT NULL,
    remaining_count INT          NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    notes           TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX idx_scheduled_task_user ON scheduled_task(user_id);
CREATE INDEX idx_scheduled_task_deadline ON scheduled_task(user_id, deadline);
