-- Seed/bulb providers (e.g. Impecta, Nelson Garden)
CREATE TABLE provider (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    identifier VARCHAR(255) NOT NULL UNIQUE
);

-- Link between species and providers, with provider-specific images and product page
CREATE TABLE species_provider (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id  BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    provider_id BIGINT NOT NULL REFERENCES provider(id) ON DELETE CASCADE,
    image_front_url TEXT,
    image_back_url  TEXT,
    product_url     TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (species_id, provider_id)
);
CREATE INDEX idx_species_provider_species ON species_provider(species_id);
CREATE INDEX idx_species_provider_provider ON species_provider(provider_id);
