-- =============================================================================
-- Organizations
-- =============================================================================

CREATE TABLE organization (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    emoji       VARCHAR(10)  DEFAULT '🌿',
    created_at  TIMESTAMPTZ  DEFAULT now(),
    updated_at  TIMESTAMPTZ  DEFAULT now()
);

CREATE TABLE org_member (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    role        VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    joined_at   TIMESTAMPTZ  DEFAULT now(),
    UNIQUE (org_id, user_id)
);

CREATE TABLE org_invite (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    email       VARCHAR(255) NOT NULL,
    invited_by  BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    status      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMPTZ  DEFAULT now(),
    UNIQUE (org_id, email)
);

-- =============================================================================
-- Drop old user_id / owner_id indexes
-- =============================================================================

DROP INDEX idx_garden_owner_id;
DROP INDEX idx_species_group_user_id;
DROP INDEX idx_species_user_id;
DROP INDEX idx_species_tag_user_id;
DROP INDEX idx_season_user_id;
DROP INDEX idx_customer_user_id;
DROP INDEX idx_plant_user_id;
DROP INDEX idx_plant_user_season;
DROP INDEX idx_frequent_comment_user_id;
DROP INDEX idx_seed_inventory_user_id;
DROP INDEX idx_succession_schedule_user_id;
DROP INDEX idx_scheduled_task_user_id;
DROP INDEX idx_pest_disease_log_user_id;
DROP INDEX idx_variety_trial_user_id;
DROP INDEX idx_bouquet_recipe_user_id;
DROP INDEX idx_production_target_user_id;
DROP INDEX idx_listing_user;
DROP INDEX idx_market_order_purchaser;
DROP INDEX idx_market_order_producer;

-- =============================================================================
-- Drop unique constraints that include user_id
-- =============================================================================

ALTER TABLE season          DROP CONSTRAINT season_user_id_name_key;
ALTER TABLE customer        DROP CONSTRAINT customer_user_id_name_key;
ALTER TABLE frequent_comment DROP CONSTRAINT frequent_comment_user_id_text_key;

-- =============================================================================
-- garden: owner_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE garden DROP COLUMN owner_id;
ALTER TABLE garden ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE garden ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- species_group: user_id -> org_id (nullable)
-- =============================================================================

ALTER TABLE species_group DROP COLUMN user_id;
ALTER TABLE species_group ADD COLUMN org_id BIGINT REFERENCES organization(id) ON DELETE CASCADE;

-- =============================================================================
-- species: user_id -> org_id (nullable)
-- =============================================================================

ALTER TABLE species DROP COLUMN user_id;
ALTER TABLE species ADD COLUMN org_id BIGINT REFERENCES organization(id) ON DELETE CASCADE;

-- =============================================================================
-- species_tag: user_id -> org_id (nullable)
-- =============================================================================

ALTER TABLE species_tag DROP COLUMN user_id;
ALTER TABLE species_tag ADD COLUMN org_id BIGINT REFERENCES organization(id) ON DELETE CASCADE;

-- =============================================================================
-- season: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE season DROP COLUMN user_id;
ALTER TABLE season ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE season ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- customer: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE customer DROP COLUMN user_id;
ALTER TABLE customer ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE customer ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- plant: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE plant DROP COLUMN user_id;
ALTER TABLE plant ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE plant ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- frequent_comment: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE frequent_comment DROP COLUMN user_id;
ALTER TABLE frequent_comment ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE frequent_comment ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- seed_inventory: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE seed_inventory DROP COLUMN user_id;
ALTER TABLE seed_inventory ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE seed_inventory ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- succession_schedule: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE succession_schedule DROP COLUMN user_id;
ALTER TABLE succession_schedule ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE succession_schedule ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- scheduled_task: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE scheduled_task DROP COLUMN user_id;
ALTER TABLE scheduled_task ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE scheduled_task ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- pest_disease_log: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE pest_disease_log DROP COLUMN user_id;
ALTER TABLE pest_disease_log ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE pest_disease_log ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- variety_trial: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE variety_trial DROP COLUMN user_id;
ALTER TABLE variety_trial ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE variety_trial ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- bouquet_recipe: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE bouquet_recipe DROP COLUMN user_id;
ALTER TABLE bouquet_recipe ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE bouquet_recipe ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- production_target: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE production_target DROP COLUMN user_id;
ALTER TABLE production_target ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE production_target ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- listing: user_id -> org_id (NOT NULL)
-- =============================================================================

ALTER TABLE listing DROP COLUMN user_id;
ALTER TABLE listing ADD COLUMN org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE listing ALTER COLUMN org_id DROP DEFAULT;

-- =============================================================================
-- market_order: purchaser_id/producer_id -> purchaser_org_id/producer_org_id
-- =============================================================================

ALTER TABLE market_order DROP COLUMN purchaser_id;
ALTER TABLE market_order DROP COLUMN producer_id;
ALTER TABLE market_order ADD COLUMN purchaser_org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE market_order ALTER COLUMN purchaser_org_id DROP DEFAULT;
ALTER TABLE market_order ADD COLUMN producer_org_id BIGINT NOT NULL DEFAULT 0 REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE market_order ALTER COLUMN producer_org_id DROP DEFAULT;

-- =============================================================================
-- New org_id indexes
-- =============================================================================

CREATE INDEX idx_organization_id ON organization(id);

CREATE INDEX idx_org_member_org_id ON org_member(org_id);
CREATE INDEX idx_org_member_user_id ON org_member(user_id);

CREATE INDEX idx_org_invite_org_id ON org_invite(org_id);

CREATE INDEX idx_garden_org_id ON garden(org_id);
CREATE INDEX idx_species_group_org_id ON species_group(org_id);
CREATE INDEX idx_species_org_id ON species(org_id);
CREATE INDEX idx_species_tag_org_id ON species_tag(org_id);
CREATE INDEX idx_season_org_id ON season(org_id);
CREATE INDEX idx_customer_org_id ON customer(org_id);
CREATE INDEX idx_plant_org_id ON plant(org_id);
CREATE INDEX idx_plant_org_season ON plant(org_id, season_id);
CREATE INDEX idx_frequent_comment_org_id ON frequent_comment(org_id);
CREATE INDEX idx_seed_inventory_org_id ON seed_inventory(org_id);
CREATE INDEX idx_succession_schedule_org_id ON succession_schedule(org_id);
CREATE INDEX idx_scheduled_task_org_id ON scheduled_task(org_id);
CREATE INDEX idx_pest_disease_log_org_id ON pest_disease_log(org_id);
CREATE INDEX idx_variety_trial_org_id ON variety_trial(org_id);
CREATE INDEX idx_bouquet_recipe_org_id ON bouquet_recipe(org_id);
CREATE INDEX idx_production_target_org_id ON production_target(org_id);
CREATE INDEX idx_listing_org ON listing(org_id);
CREATE INDEX idx_market_order_purchaser_org ON market_order(purchaser_org_id);
CREATE INDEX idx_market_order_producer_org ON market_order(producer_org_id);

-- =============================================================================
-- Recreate unique constraints using org_id
-- =============================================================================

ALTER TABLE season           ADD CONSTRAINT season_org_id_name_key           UNIQUE (org_id, name);
ALTER TABLE customer         ADD CONSTRAINT customer_org_id_name_key         UNIQUE (org_id, name);
ALTER TABLE frequent_comment ADD CONSTRAINT frequent_comment_org_id_text_key UNIQUE (org_id, text);
