#!/usr/bin/env bash
#
# Devcontainer post-create hook.
#
# 1. Sanity-check the toolchain (gradle wrapper bootstraps, Node, Android SDK).
# 2. Point Gradle at the container's Android SDK by rewriting
#    android/local.properties — the host (macOS) path baked into that
#    gitignored file by Android Studio doesn't exist inside the container.
#    Android Studio regenerates local.properties on the host the next time
#    Erik opens the project there, so this is one-way friction we accept.
#
set -euo pipefail

echo "== gradle (backend) =="
backend/gradlew --version

echo
echo "== node =="
node --version

echo
echo "== android sdk =="
if [[ -z "${ANDROID_HOME:-}" || ! -d "$ANDROID_HOME" ]]; then
  echo "ANDROID_HOME not set or missing — Android builds will fail." >&2
  exit 1
fi
sdkmanager --list_installed | sed -n '1,12p'

local_props="android/local.properties"
desired_sdk_dir="$ANDROID_HOME"
if [[ ! -f "$local_props" ]] || ! grep -qF "sdk.dir=$desired_sdk_dir" "$local_props"; then
  echo
  echo "Rewriting $local_props -> sdk.dir=$desired_sdk_dir"
  cat > "$local_props" <<EOF
# Generated by .devcontainer/post-create.sh inside the devcontainer.
# Android Studio on the host will overwrite this with the host's SDK path
# the next time it opens the project — expected.
sdk.dir=$desired_sdk_dir
EOF
fi
