package app.verdant.android.ui.task

import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CheckboxDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import app.verdant.android.data.model.ScheduledTaskResponse
import app.verdant.android.ui.faltet.FaltetListRow
import app.verdant.android.ui.maintenance.activityLabelRes
import app.verdant.android.ui.theme.FaltetAccent
import app.verdant.android.ui.theme.FaltetBerry
import app.verdant.android.ui.theme.FaltetClay
import app.verdant.android.ui.theme.FaltetForest
import app.verdant.android.ui.theme.FaltetInk
import app.verdant.android.ui.theme.FaltetMustard
import app.verdant.android.ui.theme.FaltetSage
import app.verdant.android.ui.theme.FaltetSky
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

/** Time the checked-but-not-yet-sent state is shown before the API call fires
 *  and the row animates out. Tuned so the user gets a beat of visual feedback
 *  but doesn't have to wait long. */
const val COMPLETE_TASK_DELAY_MS = 1500L

private val svDateFormatter = DateTimeFormatter.ofPattern("d MMM", Locale("sv"))

fun formatTaskDeadline(deadline: String): String = runCatching {
    LocalDate.parse(deadline).format(svDateFormatter)
}.getOrElse { deadline }

fun taskDotColor(activityType: String): Color = when (activityType) {
    "SOW" -> FaltetMustard
    "PLANT" -> FaltetSage
    "HARVEST" -> FaltetAccent
    "FERTILIZE" -> FaltetBerry
    else -> FaltetSky
}

/**
 * A task anchored to a physical place (a bed or a garden area) rather than
 * a species — WATER/WEED/FERTILIZE on a bed, or any maintenance activity
 * (MOW, RAKE, ...) on an area. These always have `targetCount == 1` and are
 * quick-completed from the list, unlike species tasks which can carry a
 * remaining count.
 */
fun isPlaceScopedTask(task: ScheduledTaskResponse): Boolean =
    task.activityType != "TODO" && (task.bedId != null || task.gardenAreaId != null)

/** The place a task is anchored to. A rule targets exactly one of a bed or
 *  a garden area, so at most one of these is ever non-null. */
fun taskPlaceName(task: ScheduledTaskResponse): String? = task.gardenAreaName ?: task.bedName

/** A task generated by a recurring maintenance rule. The server rejects
 *  `activityType`/`targetCount` edits on these — the activity belongs to
 *  the rule and the count is always 1 — and deleting one doesn't stop it:
 *  the scheduler recreates it while the rule stays active. */
fun ScheduledTaskResponse.isRuleBacked(): Boolean = maintenanceRuleId != null

/** Human-readable description of what the task targets — its place or its species. */
fun taskTargetLabel(task: ScheduledTaskResponse): String? = when {
    task.bedId != null || task.gardenAreaId != null -> taskPlaceName(task)
    else -> task.originGroupName ?: task.speciesName
}

@Composable
fun TaskRow(
    task: ScheduledTaskResponse,
    isCompleting: Boolean,
    onClick: () -> Unit,
    onCompleteToggle: () -> Unit,
    onDelete: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val isTodo = task.activityType == "TODO"
    val isPlaceTask = isPlaceScopedTask(task)
    val dotColor = taskDotColor(task.activityType)
    val title = when {
        isTodo -> task.notes?.takeIf { it.isNotBlank() } ?: "Övrigt"
        isPlaceTask -> stringResource(activityLabelRes(task.activityType))
        else -> task.originGroupName ?: task.speciesName ?: "Uppgift"
    }
    val meta = buildString {
        task.deadline?.let { append(formatTaskDeadline(it)) }
        if (isTodo) {
            // No species/place suffix for TODOs.
        } else if (isPlaceTask) {
            taskPlaceName(task)?.takeIf { it.isNotBlank() }?.let {
                if (isNotEmpty()) append(" · ")
                append(it)
            }
        } else {
            val species = task.speciesName
            if (species != null && species != title) {
                if (isNotEmpty()) append(" · ")
                append(species)
            }
        }
    }
    FaltetListRow(
        modifier = modifier,
        title = title,
        meta = meta,
        leading = {
            if (isPlaceTask || isTodo) {
                Checkbox(
                    checked = isCompleting,
                    onCheckedChange = { if (!isCompleting) onCompleteToggle() },
                    colors = CheckboxDefaults.colors(
                        checkedColor = FaltetAccent,
                        uncheckedColor = FaltetForest,
                        checkmarkColor = FaltetInk,
                    ),
                )
            } else {
                androidx.compose.foundation.layout.Box(
                    Modifier
                        .size(10.dp)
                        .drawBehind { drawCircle(dotColor) }
                )
            }
        },
        stat = if (!isPlaceTask && !isTodo) {
            {
                Row(verticalAlignment = Alignment.Bottom) {
                    Text(
                        text = task.remainingCount.toString(),
                        fontFamily = FontFamily.Monospace,
                        fontSize = 16.sp,
                        color = FaltetInk,
                    )
                    Text(
                        text = " ST",
                        fontFamily = FontFamily.Monospace,
                        fontSize = 9.sp,
                        letterSpacing = 1.2.sp,
                        color = FaltetForest,
                    )
                }
            }
        } else null,
        actions = {
            IconButton(
                onClick = onDelete,
                modifier = Modifier.size(36.dp),
            ) {
                Icon(
                    imageVector = Icons.Default.Delete,
                    contentDescription = "Ta bort",
                    tint = FaltetAccent,
                    modifier = Modifier.size(18.dp),
                )
            }
        },
        onClick = onClick,
    )
}

@Composable
fun TaskDeleteDialog(
    task: ScheduledTaskResponse,
    onConfirm: () -> Unit,
    onDismiss: () -> Unit,
) {
    val isTodo = task.activityType == "TODO"
    val title = when {
        isTodo -> task.notes?.takeIf { it.isNotBlank() } ?: "Övrigt"
        isPlaceScopedTask(task) -> stringResource(activityLabelRes(task.activityType))
        else -> task.originGroupName ?: task.speciesName ?: "Uppgift"
    }
    val target = if (isTodo) null else taskTargetLabel(task)
    val label = if (target != null && target != title) "$title · $target" else title
    // Deleting a rule-backed task does not stop it — the scheduler recreates
    // it the next morning because the underlying maintenance rule is still
    // active. Say so plainly; pausing the rule is the only way to actually
    // stop it. Never call this "dismiss"/"skip" — it isn't one.
    val message = if (task.isRuleBacked()) {
        stringResource(app.verdant.android.R.string.task_delete_rule_backed_message, label)
    } else {
        "Vill du ta bort \"$label\"?"
    }
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Ta bort uppgift") },
        text = { Text(message) },
        confirmButton = {
            TextButton(onClick = onConfirm) { Text("Ta bort", color = FaltetClay) }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) { Text("Avbryt") }
        },
    )
}
