quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=verdant
quarkus.datasource.password=verdant
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/verdant
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:5174

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=verdant-api

quarkus.log.level=INFO
